
services:
  # 数据库服务 (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: pc_inv_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432" # 映射到宿主机 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 后端 API 服务
  server:
    build: ./server
    container_name: pc_inv_server
    restart: always
    ports:
      - "5001:5000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=inventory_db
      - PORT=5000
    depends_on:
      - db

  # 前端 UI 服务
  client:
    build: ./client
    container_name: pc_inv_client
    restart: always
    ports:
      - "8090:80"
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  pgdata: